### ISSUE TITLE
Couldn't be able to run this project with flutter sdk version 1.22.6 or version 2.x on IOS

### ISSUE THREAD

**Issue by QinkangLu** [Meherdeep/agora-flutter-audio-broadcasting#1]
Which version of flutter sdk should I run this project on?
I am getting the following error running it on flutter sdk version 1.22.6
![image](https://user-images.githubusercontent.com/32942797/117364673-0bf4d980-ae73-11eb-8730-3a517113aeb8.png)
![image](https://user-images.githubusercontent.com/32942797/117364704-1911c880-ae73-11eb-863e-e1727553455b.png)

**Comment by Meherdeep** [comment]
Hey @QinkangLu ,

Thanks for raising this issue. The error that you're facing is due to missing permissions in the `info.plist` file. Can you please add the microphone and other relevant permissions to your `info.plist` file, something like this:

```
<key>NSMicrophoneUsageDescription</key>
<string>MIC</string>
```

**Comment by QinkangLu** [comment]
Thanks, it worked
